services:
  spring-boot-app:
    image: spring-boot-demo:latest  # Replace with your Spring Boot app image
    build:
      context: .  # Path to your Dockerfile
      dockerfile: Dockerfile  # Name of your Dockerfile
    ports:
      - "8080:8080"  # Expose your app on port 8080
    environment:
      - SPRING_DATA_ELASTICSEARCH_REPOSITORY_ENABLED=true
      - SPRING_ELASTICSEARCH_REST_URIS=http://elasticsearch:9200  # Point to Elasticsearch
    depends_on:
      - elasticsearch
    networks:
      app-network:


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.24
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Adjust heap size as needed
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data  # Persist data
    networks:
      app-network:
        aliases:
          - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.24
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SERVER_PORT=5601
    ports:
      - "5601:5601"
    networks:
      app-network:
        aliases:
          - kibana


volumes:
  elasticsearch-data:  # Define the volume here

networks:
  app-network:
#    driver: bridge
